import { SessionPlan } from '../types/chess';

type Section = SessionPlan['section'];

interface CurriculumSeed {
  title: string;
  section: Section;
  topics: [string, string];
  concept: string;
  analogy: string;
  practical: string;
  execution: string;
}

const C = 'CONCEPT CLASS' as const;
const G = 'GAME & REINFORCEMENT CLASS' as const;
const T = 'IN-CLASS TOURNAMENT SESSION' as const;
const O = 'OPENING & TRICKS MASTERCLASS' as const;

const seeds: CurriculumSeed[] = [
  { title: 'Meet the Board & Meet the Army', section: C, topics: ['Files, ranks, and coordinates', 'Piece names, setup, and values'], concept: 'Every square has a file letter and rank number, and every piece has a job and starting square.', analogy: 'The board is a city map and coordinates are street addresses.', practical: 'Identify 10 called-out squares and match every piece to its value.', execution: 'Set up a complete board from memory within two minutes.' },
  { title: 'Board & Army Gameplay Masterclass', section: G, topics: ['Coordinate review', 'Legal-move mini game'], concept: 'Board-reading becomes useful when students apply it while making legal moves.', analogy: 'This is a driving lesson after learning the road signs.', practical: 'Complete three coordinate and piece-value challenges.', execution: 'Play a supervised mini game using correct square names.' },
  { title: 'The Linear Movers: Rook & Bishop', section: C, topics: ['Rook ranks and files', 'Bishop diagonals and colour binding'], concept: 'Rooks move in straight lines while bishops stay on diagonals of one colour.', analogy: 'Rooks use city roads; bishops ski down diagonal slopes.', practical: 'Trace legal rook and bishop routes through obstacles.', execution: 'Explain why a bishop can never change square colour.' },
  { title: 'Rook & Bishop Gameplay Masterclass', section: G, topics: ['Open lines', 'Long-range captures'], concept: 'Long-range pieces are strongest when their paths are open.', analogy: 'A clear highway lets a fast vehicle travel farther.', practical: 'Solve three open-file and open-diagonal puzzles.', execution: 'Activate both bishops and rooks in a coached game.' },
  { title: 'The Heavy Hitters: Queen & King', section: C, topics: ['Queen movement', 'King movement and safety'], concept: 'The queen combines rook and bishop movement; the king moves one safe square at a time.', analogy: 'The queen is a superhero while the king is the protected team captain.', practical: 'Complete queen-maze and safe-king exercises.', execution: 'Distinguish a legal king move from a move into check.' },
  { title: 'Queen & King Gameplay Masterclass', section: G, topics: ['Queen activity', 'Safe king decisions'], concept: 'Powerful queen moves must be balanced with king safety.', analogy: 'Score goals without leaving your goalkeeper unprotected.', practical: 'Solve three queen-target and king-safety positions.', execution: 'Finish a mini game without exposing the king illegally.' },
  { title: 'Milestone 1 Welcome Tournament', section: T, topics: ['Clock basics', 'Sportsmanship'], concept: 'A structured tournament turns rules knowledge into calm competitive habits.', analogy: 'Like a school sports day: compete hard, respect everyone.', practical: 'Complete three short paired games.', execution: 'Use the clock correctly and record every result.' },
  { title: 'The Brave Pawn', section: C, topics: ['One- and two-square advances', 'Diagonal captures'], concept: 'Pawns move forward, capture diagonally, and never move backward.', analogy: 'Pawns are explorers who march ahead and collect treasure sideways.', practical: 'Choose the legal pawn move in eight positions.', execution: 'Demonstrate initial double moves and diagonal captures.' },
  { title: 'Pawn Power Gameplay', section: G, topics: ['Pawn chains', 'Healthy pawn trades'], concept: 'Connected pawns protect one another and create space.', analogy: 'A linked hiking team is safer than one person walking alone.', practical: 'Build three connected pawn chains.', execution: 'Play a pawn-only race and promote first.' },
  { title: 'Check! The CPR Defence Rules', section: C, topics: ['Recognising check', 'Capture, Protect/Block, Run'], concept: 'A checked king must respond immediately by capturing, blocking, or moving away.', analogy: 'Check is an alarm and CPR is the emergency plan.', practical: 'Classify twelve positions as safe or check.', execution: 'Name and play every legal CPR response in sample positions.' },
  { title: 'Escaping Check Gameplay', section: G, topics: ['Selecting a CPR response', 'Avoiding illegal replies'], concept: 'The best check defence is the safest legal response, not always the first move seen.', analogy: 'Choose the safest emergency exit, not merely the nearest door.', practical: 'Solve six check-defence puzzles.', execution: 'Play a mini game with zero ignored checks.' },
  { title: 'Checkmate vs Stalemate', section: C, topics: ['Checkmate conditions', 'Stalemate and draw'], concept: 'Checkmate has check and no escape; stalemate has no check and no legal move.', analogy: 'Checkmate is capture by the rules; stalemate is a traffic jam with no route.', practical: 'Sort ten endings into checkmate, stalemate, or ongoing.', execution: 'Explain the decisive difference using a board position.' },
  { title: 'Mate in One Pattern Hunt', section: G, topics: ['King escape squares', 'Protected checking pieces'], concept: 'A mating move checks the king and covers every escape or defence.', analogy: 'Close every door before ringing the final bell.', practical: 'Solve eight mate-in-one puzzles.', execution: 'Verify check, captures, blocks, and escapes before answering.' },
  { title: 'King & Queen Checkmate', section: C, topics: ['Box method', 'Avoiding stalemate'], concept: 'The queen reduces the king’s space while the friendly king provides final support.', analogy: 'Build a smaller fence without trapping the animal too early.', practical: 'Shrink the king box in four positions.', execution: 'Deliver king-and-queen mate from a standard setup.' },
  { title: 'King & Rook Checkmate', section: C, topics: ['Opposition', 'Rook box method'], concept: 'The rook makes a wall and the king forces the opponent toward the edge.', analogy: 'One player builds a wall while the other walks the opponent backward.', practical: 'Coordinate king and rook in four drills.', execution: 'Deliver the basic rook mate within a move limit.' },
  { title: 'Basic Mates Gameplay Lab', section: G, topics: ['Queen mate practice', 'Rook mate practice'], concept: 'Repeated correct technique turns winning material into a reliable result.', analogy: 'Practise landing the plane, not only flying it.', practical: 'Complete both basic-mate drills against resistance.', execution: 'Avoid stalemate in every attempt.' },
  { title: 'Opening Principles', section: C, topics: ['Centre, development, king safety', 'Avoiding repeated moves'], concept: 'Good openings control the centre, develop pieces, castle, and connect rooks.', analogy: 'Prepare the whole team before launching an attack.', practical: 'Rank opening moves by principle.', execution: 'Reach a developed, castled position within ten moves.' },
  { title: 'Opening Principles Gameplay', section: G, topics: ['Development race', 'Opening self-check'], concept: 'Students learn to measure development rather than memorise random moves.', analogy: 'A pre-flight checklist prevents avoidable mistakes.', practical: 'Audit three opening positions.', execution: 'Play a game while completing the opening checklist.' },
  { title: 'Tactical Motif: The Knight Fork', section: C, topics: ['Double attacks', 'Royal forks'], concept: 'A knight can attack two valuable targets from one landing square.', analogy: 'One fork picks up two pieces of food at once.', practical: 'Spot six knight-fork squares.', execution: 'Execute a royal fork with check.' },
  { title: 'Forks Gameplay Lab', section: G, topics: ['Creating forks', 'Preventing forks'], concept: 'Fork skill includes noticing both your opportunity and your opponent’s threat.', analogy: 'Look both ways before crossing the tactical road.', practical: 'Solve attacking and defensive fork puzzles.', execution: 'Create or prevent a fork in a coached game.' },
  { title: 'Tactical Motif: The Pin', section: C, topics: ['Absolute pins', 'Relative pins'], concept: 'A pinned piece cannot or should not move because a more valuable piece sits behind it.', analogy: 'A safety pin holds one layer in front of another.', practical: 'Identify absolute and relative pins.', execution: 'Create a pin and increase pressure on the pinned piece.' },
  { title: 'Pins Gameplay Lab', section: G, topics: ['Breaking pins', 'Winning pinned pieces'], concept: 'Pins become valuable when attackers are added and defenders are removed.', analogy: 'One clamp holds; extra pressure makes it useful.', practical: 'Solve six pin-and-unpin puzzles.', execution: 'Exploit a pin without overlooking a counterattack.' },
  { title: 'Tactical Motif: The Skewer', section: C, topics: ['High-value front target', 'Winning the piece behind'], concept: 'A skewer attacks a valuable piece first and collects the piece behind after it moves.', analogy: 'The front object slides away and reveals the prize behind it.', practical: 'Distinguish skewers from pins in eight diagrams.', execution: 'Play a forcing skewer sequence correctly.' },
  { title: 'Skewers Gameplay Lab', section: G, topics: ['Forcing moves', 'Line-piece geometry'], concept: 'Checks and attacks on queens often make skewers forcing.', analogy: 'Move the biggest obstacle to open the straight road.', practical: 'Solve rook, bishop, and queen skewers.', execution: 'Create a skewer from a game-like position.' },
  { title: 'Discovered Attacks', section: C, topics: ['Moving the blocker', 'Discovered check'], concept: 'Moving one piece can reveal an attack from a line piece behind it.', analogy: 'Open a curtain and the spotlight behind it suddenly shines.', practical: 'Find six discovered attacks.', execution: 'Use a discovered check to gain material.' },
  { title: 'Discovery Gameplay Lab', section: G, topics: ['Double threats', 'Safe clearance moves'], concept: 'The moving piece and revealed piece can threaten different targets simultaneously.', analogy: 'Two teammates start separate attacks with one signal.', practical: 'Calculate four two-threat discoveries.', execution: 'Play the clearance move without hanging the moving piece.' },
  { title: 'Combining Tactical Motifs', section: C, topics: ['Candidate moves', 'Two-motif combinations'], concept: 'Strong tactics often combine checks, captures, threats, and more than one motif.', analogy: 'A combo move in a game links two powers together.', practical: 'Label the motifs in six combinations.', execution: 'Calculate a three-move forcing line.' },
  { title: 'Milestone 2 Tactics Tournament', section: T, topics: ['Puzzle race', 'Tactical game review'], concept: 'Competition under a friendly clock tests pattern recognition and accuracy.', analogy: 'A skills relay rewards both speed and clean technique.', practical: 'Complete a rated puzzle circuit.', execution: 'Explain one tactic from a tournament game.' },
  { title: 'Castling & King Safety', section: C, topics: ['Castling rules', 'When not to castle'], concept: 'Castling moves king and rook together when the path, check, and movement rules permit it.', analogy: 'The king enters a castle while the rook reaches the open road.', practical: 'Judge legal castling in eight positions.', execution: 'Castle at an appropriate time in a game.' },
  { title: 'King Safety Gameplay', section: G, topics: ['Pawn shield', 'Opening lines near the king'], concept: 'A safe king needs defenders, a healthy pawn shield, and awareness of open files and diagonals.', analogy: 'A house is safest with walls, guards, and closed doors.', practical: 'Repair four unsafe king positions.', execution: 'Launch an attack without weakening the own king.' },
  { title: 'Special Pawn Rules', section: C, topics: ['Promotion', 'En passant'], concept: 'Promotion rewards a pawn reaching the last rank; en passant is a one-move response to a double advance.', analogy: 'Graduation creates a new role; en passant is a time-limited ticket.', practical: 'Apply both special rules in sample positions.', execution: 'State exactly when the en-passant right expires.' },
  { title: 'Promotion Race Gameplay', section: G, topics: ['Counting pawn moves', 'Choosing a promotion piece'], concept: 'Pawn races require precise counting, checks, and awareness of underpromotion.', analogy: 'Two runners race, but a tactical shortcut can change the finish.', practical: 'Calculate five pawn races.', execution: 'Choose queen or underpromotion for the correct result.' },
  { title: 'King Opposition', section: C, topics: ['Direct opposition', 'Key squares'], concept: 'Kings facing each other use opposition to control entry squares in pawn endings.', analogy: 'Two door guards compete to make the other step aside.', practical: 'Win opposition in six positions.', execution: 'Use a key square to support pawn promotion.' },
  { title: 'King & Pawn Endgames', section: G, topics: ['Rule of the square', 'King in front of the pawn'], concept: 'Simple pawn endings depend on king activity, opposition, and accurate counting.', analogy: 'Escort the pawn like a guide walking a child safely home.', practical: 'Classify basic endings as win or draw.', execution: 'Convert a winning king-and-pawn ending.' },
  { title: 'Passed Pawns', section: C, topics: ['Creating passed pawns', 'Blockading'], concept: 'A passed pawn has no enemy pawn able to stop it on neighbouring files.', analogy: 'A runner has a clear lane to the finish.', practical: 'Create a passed pawn through exchanges.', execution: 'Blockade an opponent’s passer with the best piece.' },
  { title: 'Milestone 3 Endgame Challenge', section: T, topics: ['Endgame stations', 'Technique under time'], concept: 'Students rotate through basic mates, pawn endings, and promotion races.', analogy: 'An endgame obstacle course tests every finishing skill.', practical: 'Complete four assessed endgame stations.', execution: 'Score at least 75% with correct technique.' },
  { title: 'Reading & Writing Chess Notation', section: C, topics: ['Algebraic notation', 'Captures, checks, and mate symbols'], concept: 'Notation records the piece, destination, capture, promotion, check, and mate information compactly.', analogy: 'Chess notation is the game’s universal written language.', practical: 'Translate twelve moves between board and notation.', execution: 'Record a complete mini game accurately.' },
  { title: 'Game Recording & Review', section: G, topics: ['Score sheets', 'Finding turning points'], concept: 'Recorded games allow students to replace guesses with evidence during review.', analogy: 'A match replay helps the team find what to practise next.', practical: 'Annotate three key moments in a game.', execution: 'Name one strength and one improvement goal from evidence.' },
  { title: 'Scholar’s Mate: Attack & Defence', section: O, topics: ['Early queen threats', 'Safe defensive development'], concept: 'Scholar’s Mate teaches f7/f2 awareness but early queen adventures can lose time.', analogy: 'A quick trick works only when the defender ignores the alarm.', practical: 'Defend the threat in four different positions.', execution: 'Develop safely while attacking the exposed queen.' },
  { title: 'Opening Traps & Trap Safety', section: O, topics: ['Threat verification', 'Poisoned material'], concept: 'Before accepting free material, students check the opponent’s forcing reply.', analogy: 'A shiny gift may have a string attached.', practical: 'Separate sound tactics from unsound traps.', execution: 'Use checks, captures, and threats to verify a move.' },
  { title: 'The Italian Game', section: O, topics: ['e4, Nf3, Bc4 setup', 'Pressure on f7'], concept: 'The Italian Game develops quickly, controls the centre, and prepares castling.', analogy: 'Bring pieces onto useful roads before starting the attack.', practical: 'Build the Italian setup from memory.', execution: 'Explain the purpose of each opening move.' },
  { title: 'Italian Game Gameplay', section: G, topics: ['Central breaks', 'Piece coordination'], concept: 'Italian positions reward patient development and well-timed central action.', analogy: 'Arrange the team, then open the gate at the right moment.', practical: 'Choose plans in four Italian positions.', execution: 'Play a reviewed game from the Italian setup.' },
  { title: 'The London System', section: O, topics: ['d4, Nf3, Bf4 setup', 'Solid pawn triangle'], concept: 'The London builds a repeatable structure while still requiring attention to the opponent.', analogy: 'A dependable house plan must still fit the land around it.', practical: 'Build the core London structure.', execution: 'Adapt development when the opponent changes setup.' },
  { title: 'London System Gameplay', section: G, topics: ['Typical plans', 'Kingside and central play'], concept: 'The London’s structure supports several plans rather than one automatic attack.', analogy: 'The same base camp can lead to different hiking routes.', practical: 'Select a plan in four London positions.', execution: 'Complete development before beginning an attack.' },
  { title: 'Calculation: Checks, Captures, Threats', section: C, topics: ['Candidate moves', 'Visualising replies'], concept: 'A disciplined calculation process starts with forcing candidates and tests the opponent’s best reply.', analogy: 'Before choosing a route, inspect every fast road and obstacle.', practical: 'Calculate six positions without moving pieces.', execution: 'Give a complete three-ply line with evaluation.' },
  { title: 'Clock Management & Sportsmanship', section: G, topics: ['Time budgeting', 'Tournament etiquette'], concept: 'Strong tournament play balances thinking time, legal procedure, and respectful behaviour.', analogy: 'Use water steadily through a long race instead of all at once.', practical: 'Complete timed decision drills.', execution: 'Play a clocked game with correct etiquette.' },
  { title: 'Championship Preparation', section: G, topics: ['Personal checklist', 'Opening and endgame review'], concept: 'Preparation combines a calm routine, familiar positions, and a plan for mistakes.', analogy: 'Pack the right tools before the final expedition.', practical: 'Complete a personalised readiness checklist.', execution: 'Demonstrate one opening, tactic, and endgame technique.' },
  { title: 'Graduation Championship', section: T, topics: ['Multi-round tournament', 'Reflection and next goals'], concept: 'The final event celebrates complete games, independent decisions, resilience, and reflection.', analogy: 'Graduation is both a finish line and the start of the next level.', practical: 'Complete the championship and submit all results.', execution: 'Present a favourite game and a measurable next goal.' }
];

export const FULL_BEGINNER_CURRICULUM: SessionPlan[] = seeds.map((seed, index) => {
  const sessionNumber = index + 1;
  const gameClass = seed.section === G || seed.section === T;
  return {
    sessionNumber,
    title: seed.title,
    section: seed.section,
    primaryTool: gameClass ? 'Unbox Chess Interactive Board & Game Arena' : 'Unbox Chess Guided Lesson & Puzzle Studio',
    topics: seed.topics,
    coreConcept: seed.concept,
    kidExplanation: seed.concept,
    analogy: seed.analogy,
    outcomeA: seed.practical,
    outcomeB: seed.execution,
    lessonSteps: [
      { step: '1', title: 'Connect & Recall (5 min)', description: `Review the previous skill and introduce today’s goal: ${seed.title}.` },
      { step: '2', title: 'Coach Demonstration (10 min)', description: `Model ${seed.topics[0].toLowerCase()} with student prediction checks and clear board language.` },
      { step: '3', title: 'Guided Practice (10 min)', description: `Complete scaffolded activities on ${seed.topics[1].toLowerCase()} and correct misconceptions immediately.` },
      { step: '4', title: 'Independent Application (20 min)', description: `${seed.practical} The platform records accuracy, attempts, hints, and completion time.` },
      { step: '5', title: 'Review & Exit Check (5 min)', description: `${seed.execution} Record the result and set the next practice target.` }
    ]
  };
});

if (FULL_BEGINNER_CURRICULUM.length !== 48) {
  throw new Error(`Curriculum must contain exactly 48 sessions; received ${FULL_BEGINNER_CURRICULUM.length}.`);
}
